
/**
* Function apply_mask
* -------------------
* The function creats unique masks in turn creates a unique Sudoku game.
* Numbers are masked from the rearranged 2D array locations based on diffculty level. The difficulty levels are catagorized as easy, medium, hard,
* and very hard, where the easy game only shows 40 numbers, the medium 34 numbers, the hard game 28 and finally the very hard one only 24 numbers
* showing. The Sudoku game is made of 9x9 matrix with total of 81 cells. The algorithm of this function employs the C random number generator
* to generate a number between 1 to 81, where each number represens location at the 2D array and these randomly generated numbers are then used to
* map to locations of the rearranged_sudoku array to mask (initialozed to zero) of the array locations.
* Language C
* @param rearranged_sudoku [in], the 2D array containing the rearranged Sudoku game.
* @param cells_to_remain [in], he amount of numbers that should remain after masking.
* @param masked_sudoku [out], the 2D array containing the masked Sudoku game.
* Author Gabriel Seyoum, Group-H member, student # 100333091
* Date May 31, 2020
*/
void apply_mask(int rearranged_sudoku [9][9], int cells_to_remain, int masked_sudoku [9][9]){
    int total_num_cells = 81;                                          /* To hold information  about each cell in the Sudoku game */
    int cells_tobe_removed = total_num_cells - cells_to_remain;        /* Holdes the number of cells that needed to be masked */
    int l = 0, m = 0, random_cell;                                     /* Variable l and m holds the index location of cells to be masked */
                                                                       /* random_cell holds the random number generated */
    int random_cell_locations [81];                                    /* random_cell_locations holds randomly selected cell locations */
    int track_duplicate_random_num[cells_tobe_removed];                /* track_duplicate_random_num check to track no duplicate data is generated by random function */
    int *ptr = random_cell_locations;

    /* Arrays being initialized */
    for(int i = 0; i < 9; i++){
        for(int j = 0; j < 9; j++){
            masked_sudoku [i][j] = rearranged_sudoku [i][j];
        }
     }

     for(int i = 0; i < total_num_cells-1; i++){
         random_cell_locations[i] = 0;
         track_duplicate_random_num [i] = 0;
     }

    /** Here cells are selected using C random function, the game being 9x9, it has 81 cells total. Based on difficulty level
       cells are chosen radomly between 1 to 81 and these values are employed to mask numbers at particular cell locations
    */
    for(int k = 0; k < cells_tobe_removed; k++){
        random_cell = (rand() % (81 - 1 + 1)) + 1;

        track_duplicate_random_num[k] = random_cell;

        if(k == 0){
            random_cell_locations[random_cell - 1] = random_cell;
        }

        /** Here the code checks if duplicate random numbers are generated and re-enforces no duplicate random number rule.
         */
        for(int y = k  ; y >0 ; y--){
            if((track_duplicate_random_num[k]) == track_duplicate_random_num[y-1]){
               --k;
            }
            else{
                random_cell_locations[random_cell - 1] = random_cell;
        }
    }
}
    /** Here randomly chosen cell locations are mapped to the actual game cell location, using the randomly selected numbers the
     *  following code will use l and m indexes value to locate a cell to mask.
     */
    for(ptr = &random_cell_locations[0]; ptr <= &random_cell_locations[total_num_cells - 1]; ptr++){
        if (*ptr != 0){
             masked_sudoku[l][m] = '\0';
        }
        m++;
        if(m == 9){
            l++;
            m = 0;
        }
    }
}
