/**
* Function apply_mask
* -------------------
* Function apply_mask creates unique masks in turn creates a unique Sudoku game.
* Numbers are masked from the rearranged 2D array locations based on diffculty level. 
* Language: C
* Author: Gabriel Seyoum, Group H member
* Date: May 31, 2020
*/

#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "../include/sudoku.h"

/**
* @param rearranged_sudoku [in], Array containing the rearranged Sudoku game.
* @param cells_tobe_masked [in], Number of cells that needed to be masked.
* @param masked_sudoku [out], Array containing the masked Sudoku game.
*/
void apply_mask(int rearranged_sudoku [9][9], int cells_tobe_masked, int masked_sudoku [9][9]){
    int total_num_cells = 81;                                       /* total_num_cells ... total number of cells in the Sudoku game */
    int l = 0, m = 0, random_cell;                                  /* l and m ... index location of cells to be masked, random_cell ... random numbers between 1 to 81 to be used for masking*/
    int random_cell_locations [81];                                 /* random_cell_locations ... to store all the randomly selected cell locations */
    int track_duplicate_random_num[cells_tobe_masked];              /* track_duplicate_random_num ... to track no duplicate data is generated by random number generator*/
    int *ptr = random_cell_locations;

    /* Array initialization */
    for(int i = 0; i < 9; i++){
        for(int j = 0; j < 9; j++){
            masked_sudoku [i][j] = rearranged_sudoku [i][j];
        }
     }

     for(int i = 0; i < total_num_cells-1; i++){
         random_cell_locations[i] = 0;
         track_duplicate_random_num [i] = 0;
     }

    /*Based on difficulty level cells are chosen radomly between 1 to 81, these values are then used to mask Sudoku game cell locations*/
    for(int k = 0; k < cells_tobe_masked; k++){
        random_cell = (rand() % (81 - 1 + 1)) + 1;

        track_duplicate_random_num[k] = random_cell;

        if(k == 0){
            random_cell_locations[random_cell - 1] = random_cell;
        }

        /*The following code checks if duplicate random numbers are generated, if yes re-enforces no duplicate random numbers from being used to map cell locatio*/
        for(int y = k  ; y >0 ; y--){
            if((track_duplicate_random_num[k]) == track_duplicate_random_num[y-1]){
               --k;
            }
            else{
                random_cell_locations[random_cell - 1] = random_cell;
        }
    }
}
    /*Randomly chosen cell locations are mapped to the actual Sudoku game cell locations to mask some of the numbers based on the difficulty level*/
    for(ptr = &random_cell_locations[0]; ptr <= &random_cell_locations[total_num_cells - 1]; ptr++){
        if (*ptr != 0){
             masked_sudoku[l][m] = '\0';
        }
        m++;
        if(m == 9){
            l++;
            m = 0;
        }
    }
}

